# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main-test:
    name: Main test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Running tests
        run: yarn test

  ember-try-required:
    name: Ember try ember-${{matrix.scenario}}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        scenario: [ember-lts-3.8, ember-lts-3.12, ember-lts-3.16, ember-lts-3.20]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Running test
        run: yarn ember try:one ${{ matrix.scenario }}

  ember-try-optional:
    name: Ember try ember-${{matrix.scenario}}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        scenario: [ember-beta, ember-release, ember-canary, embroider-safe, embroider-optimized]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Running test
        run: yarn ember try:one ${{ matrix.scenario }}
        continue-on-error: true
